version: '3.8'

services:
  north-bot:
    build: .
    container_name: respect-north-bot
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HF_API_KEY=${HF_API_KEY}
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"

volumes:
  data:
